// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtuajaadwpvagbtytalj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0dWFqYWFkd3B2YWdidHl0YWxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NzY4MTYsImV4cCI6MjA2MzE1MjgxNn0.3SRG-3nx8s59CC155ox1ZxCTZOCJor3BrK9dp67zsFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);